name: Deploy to Production

on:
  workflow_dispatch:

env:
  DOCKER_COMPOSE_FILE: docker-compose.yml
  SSH_USER: ${{ secrets.PRODUCTION_USER || 'root' }}
  SSH_PORT: ${{ secrets.PRODUCTION_PORT || 58320 }}


jobs:
  deploy-server1:
    name: "Deploy - Server 1"
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.deploy.outputs.result }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server 1
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER1_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            echo "ğŸ”„ æ­£åœ¨æ‹‰å–æœ€æ–°ä»£ç ..."
            cd /mnt/nfs/lobe-chat  # æ›´æ”¹ä¸ºä½ çš„æœåŠ¡å™¨é¡¹ç›®è·¯å¾„
            git pull

            echo "ğŸ”§ æ›´æ–° Docker å®¹å™¨..."
            docker-compose pull && docker-compose up -d --scale lobe-chat=2 --no-recreate
            docker-compose up -d --scale lobe-chat=1
            echo "âœ… éƒ¨ç½²æˆåŠŸï¼"
            docker-compose ps

            docker image prune -f

#  deploy-server2:
#    name: "Deploy - Server 2"
#    runs-on: ubuntu-latest
#    needs: deploy-server1  # æ˜ç¡®ä¾èµ–å…³ç³»
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Deploy to Server 2
#        uses: appleboy/ssh-action@v1.0.0
#        with:
#          host: ${{ secrets.SERVER2_HOST }}
#          username: ${{ env.SSH_USER }}
#          key: ${{ secrets.PRODUCTION_SSH_KEY }}
#          port: ${{ env.SSH_PORT }}
#          script: |
#            echo "ğŸ”„ æ­£åœ¨æ‹‰å–æœ€æ–°ä»£ç ..."
#            cd /mnt/nfs/lobe-chat  # æ›´æ”¹ä¸ºä½ çš„æœåŠ¡å™¨é¡¹ç›®è·¯å¾„
#            git pull
#
#            echo "ğŸ”§ æ›´æ–° Docker å®¹å™¨..."
#            docker-compose pull && docker-compose up -d && docker image prune -f  # å¦‚æœä½¿ç”¨è¿œç¨‹é•œåƒä»“åº“
#
#            echo "âœ… éƒ¨ç½²æˆåŠŸï¼"
#            docker-compose ps
