name: Issue Auto Comment
on:
  issues:
    types:
      - opened
      - closed
      - assigned
  pull_request_target:
    types:
      - opened
      - closed

permissions:
  contents: read

jobs:
  run:
    permissions:
      issues: write # for actions-cool/issues-helper to update issues
      pull-requests: write # for actions-cool/issues-helper to update PRs
    runs-on: ubuntu-latest
    steps:
      - name: Auto Comment on Issues Opened
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
          issuesOpened: |
            ğŸ‘€ @{{ author }}

            Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible.
            Please make sure you have given us as much context as possible.\
            éå¸¸æ„Ÿè°¢æ‚¨æäº¤ issueã€‚æˆ‘ä»¬ä¼šå°½å¿«è°ƒæŸ¥æ­¤äº‹ï¼Œå¹¶å°½å¿«å›å¤æ‚¨ã€‚ è¯·ç¡®ä¿æ‚¨å·²ç»æä¾›äº†å°½å¯èƒ½å¤šçš„èƒŒæ™¯ä¿¡æ¯ã€‚
      - name: Auto Comment on Issues Closed
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
          issuesClosed: |
            âœ… @{{ author }}

            This issue is closed, If you have any questions, you can comment and reply.\
            æ­¤é—®é¢˜å·²ç»å…³é—­ã€‚å¦‚æœæ‚¨æœ‰ä»»ä½•é—®é¢˜ï¼Œå¯ä»¥ç•™è¨€å¹¶å›å¤ã€‚
      - name: Auto Comment on Pull Request Opened
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
          pullRequestOpened: |
            ğŸ‘ @{{ author }}

            Thank you for raising your pull request and contributing to our Community
            Please make sure you have followed our contributing guidelines. We will review it as soon as possible.
            If you encounter any problems, please feel free to connect with us.\
            éå¸¸æ„Ÿè°¢æ‚¨æå‡ºæ‹‰å–è¯·æ±‚å¹¶ä¸ºæˆ‘ä»¬çš„ç¤¾åŒºåšå‡ºè´¡çŒ®ï¼Œè¯·ç¡®ä¿æ‚¨å·²ç»éµå¾ªäº†æˆ‘ä»¬çš„è´¡çŒ®æŒ‡å—ï¼Œæˆ‘ä»¬ä¼šå°½å¿«å®¡æŸ¥å®ƒã€‚
            å¦‚æœæ‚¨é‡åˆ°ä»»ä½•é—®é¢˜ï¼Œè¯·éšæ—¶ä¸æˆ‘ä»¬è”ç³»ã€‚
      - name: Auto Comment on Pull Request Merged
        uses: actions-cool/pr-welcome@main
        if: github.event.pull_request.merged == true
        with:
          token: ${{ secrets.GH_TOKEN }}
          comment: |
            â¤ï¸ Great PR @${{ github.event.pull_request.user.login }} â¤ï¸

            The growth of project is inseparable from user feedback and contribution, thanks for your contribution! If you are interesting with the lobehub developer community, please join our [discord](https://discord.com/invite/AYFPHvv2jT) and then dm @arvinxx or @canisminor1990. They will invite you to our private developer channel. We are talking about the lobe-chat development or sharing ai newsletter around the world.\
            é¡¹ç›®çš„æˆé•¿ç¦»ä¸å¼€ç”¨æˆ·åé¦ˆå’Œè´¡çŒ®ï¼Œæ„Ÿè°¢æ‚¨çš„è´¡çŒ®! å¦‚æœæ‚¨å¯¹ LobeHub å¼€å‘è€…ç¤¾åŒºæ„Ÿå…´è¶£ï¼Œè¯·åŠ å…¥æˆ‘ä»¬çš„ [discord](https://discord.com/invite/AYFPHvv2jT)ï¼Œç„¶åç§ä¿¡ @arvinxx æˆ– @canisminor1990ã€‚ä»–ä»¬ä¼šé‚€è¯·æ‚¨åŠ å…¥æˆ‘ä»¬çš„ç§å¯†å¼€å‘è€…é¢‘é“ã€‚æˆ‘ä»¬å°†ä¼šè®¨è®ºå…³äº Lobe Chat çš„å¼€å‘ï¼Œåˆ†äº«å’Œè®¨è®ºå…¨çƒèŒƒå›´å†…çš„ AI æ¶ˆæ¯ã€‚
          emoji: 'hooray'
          pr-emoji: '+1, heart'
      - name: Remove inactive
        if: github.event.issue.state == 'open' && github.actor == github.event.issue.user.login
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'Inactive'
